### PR TITLE
change annotation from field to fields in sample

### PR DESCRIPTION
**Pull request by ersin-ertan**

### CODE REVIEW

**Comment by sockeqwe** [comment]
Thanks!

**Comment by ersin-ertan** [comment]
My pleasure. I'm going through some of [your libraries one by one](https://github.com/ersin-ertan/SockeqweExamples) and trying out the samples/reading docs. Next is AdapterDelegates(was an illustrative blog post)

**Comment by sockeqwe** [comment]
I should spend more time on creating "bug free / compileable" readme files. sorry ...

**Comment by ersin-ertan** [comment]
I think that your libraries address common problems with a great degree of elegance and wish for others to see so as well, thus for other developers trying out the samples, their UX(first impression) is an important consideration.

**Pull request merged**
